language: cpp
os:
  - osx
  - linux
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  file:
    - "emmy_core/emmy_core.so"
    - "emmy_core/emmy_core.dylib"
  skip_cleanup: true
  draft: false
  on:
    tags: true