language: cpp
os:
  - osx
  - linux
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  file: "emmy_core/Debug/emmy_core.so"
  skip_cleanup: true
  on:
    tags: true