name: Emmy Debugger Core

on: [push]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Build x86
      run: |
        mkdir x86
        cd x86
        cmake ..  -A Win32 -G "Visual Studio 17 2022"
        cmake --build . --config RelWithDebInfo --target install
    
    - name: Upload x86
      uses: actions/upload-artifact@v1.0.0
      with:
        name: x86
        path: x86/install/bin

    - name: Build x64
      run: |
        mkdir x64
        cd x64
        cmake ../ -A Win64 -G "Visual Studio 17 2022"
        cmake --build . --config RelWithDebInfo --target install
    
    - name: Upload x64
      uses: actions/upload-artifact@v1.0.0
      with:
        name: x64
        path: x64/install/bin

  build-other:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, target: linux, platform: linux-x64}
          - { os: macos-latest, target: darwin, platform: darwin-x64}
          - { os: macos-latest, target: darwin, platform: darwin-arm64}
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cmake --install . --config Release --prefix ${{ github.workspace }}/artifact/
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.platform }}
        path: ${{ github.workspace }}/artifact/
 
  upload-release:
    name: Upload Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-other]
    runs-on: [ubuntu-18.04]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@master
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ github.ref }}
          draft: true
          prerelease: true
      
      - name: Download Windows-x86
        uses: actions/download-artifact@v1.0.0
        with:
          name: x86
          path: artifact/x86
      
      - name: Zip x86
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          filename: emmy_core@x86.zip
          path: artifact/x86
      
      - name: Upload x86
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: emmy_core@x86.zip
          asset_name: emmy_core@x86.zip
          asset_content_type: application/tar+gzip
      
      - name: Download Windows-x64
        uses: actions/download-artifact@v1.0.0
        with:
          name: x64
          path: artifact/x64
      
      - name: Zip x64
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          filename: emmy_core@x64.zip
          path: artifact/x64
      
      - name: Upload x64
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: emmy_core@x64.zip
          asset_name: emmy_core@x64.zip
          asset_content_type: application/tar+gzip
          
      - name: Download so
        uses: actions/download-artifact@v1.0.0
        with:
          name: emmy_core.so
          path: artifact
      
      - name: Upload so
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact/emmy_core.so
          asset_name: emmy_core.so
          asset_content_type: application/gzip
      
      - name: Download dylib
        uses: actions/download-artifact@v1.0.0
        with:
          name: emmy_core.dylib
          path: artifact
      
      - name: Upload dylib
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact/emmy_core.dylib
          asset_name: emmy_core.dylib
          asset_content_type: application/gzip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: EmmyLuaDebugger
          draft: false
          generate_release_notes: true
          files: |
            linux-x64.zip
            darwin-x64.zip
            darwin-arm64.zip
            win32-x64.zip
          token: ${{ secrets.RELEASE }}
